<?php

include_once('cmtls_dashboard.features.inc');

function cmtls_dashboard_cmtls_app()
{
	return array(
		'cmtls_dashboard' => array(
			'title' => t('Dashboard'),
			'callback' => 'cmtls_dashboard_page',
		),
	);
}

function cmtls_dashboard_cmtls_map_config()
{
	return array(
		'cmtls_dashboard' => array(
			'map views' => array(
				CMTLS_MAP_NONE,
				CMTLS_MAP_VIEW_HIDDEN,
				CMTLS_MAP_VIEW_HALF_PAGE,
				CMTLS_MAP_VIEW_FULL_PAGE,
			),
			'default map view' => CMTLS_MAP_VIEW_HIDDEN,
			'map view changable' => TRUE,
		),
	);
}

function cmtls_dashboard_page($app_id)
{
	$group = _cmtls_group_get_current();
	
	$build = '<div id="text-container"><div class="dashboard-1">';
	
	// get all groups apps
	$result = db_query('SELECT nodehierarchy.nid FROM {nodehierarchy} nodehierarchy WHERE nodehierarchy.parent = '.(int)$group->nid.' ORDER BY order_by');
	
	// app blocks
	while($row = db_fetch_array($result))
	{
		$app = node_load($row['nid']);
		
		$content = module_invoke($app->field_cmtls_app_type[0]['value'], 'cmtls_dashboard_block_content', $group, $app);
		
		if($content)
		{
			$build .= '<div class="dashboard-item"><div class="content">';
			$build .= '<div class="title">'.$app->title.'</div>';
			$build .= l(t('See all'), 'cmtls/'.$group->nid.'/'.$app->nid, array('attributes' => array('class' => 'see-all-link')));
			$build .= $content;
			$build .= '</div></div>';
		}
	}
	$build .= '</div>';
	
	// widgets
	$widgets = module_invoke_all('cmtls_dashboard_widgets', $group);
	
	if(sizeof($widgets))
	{
		$build .= '<div class="dashboard-2">';
	
		foreach($widgets as $widget)
		{
			$build .= '<div class="dashboard-item"><div class="content">';
			$build .= '<div class="title">'.$widget['title'].'</div>';
			//$build .= l('Vaata koiki', 'cmtls/'.$group->nid.'/'.$app->nid, array('attributes' => array('class' => 'see-all-link')));
			$build .= $widget['content'];
			$build .= '</div></div>';
		}
		
		$build .= '</div></div><!-- text-container -->';
	}
				//	lisas kommentaari artiklile
	
	return $build;
}

function hook_cmtls_dashboard_block_content($group, $app)
{
	return views_embed_view('example_view', 'example_display_id', $group->nid, $app->nid);
}

function hook_cmtls_dashboard_widgets($group)
{
	return array(
		'example_widget' => array(
			'title' => 'Example title',
			'content' => views_embed_view('example_view', 'example_display_id', $group->nid),
		),
	);
}