<?php

include_once('cmtls_dashboard.features.inc');

function cmtls_dashboard_cmtls_app()
{
	return array(
		'cmtls_dashboard' => array(
			'title' => t('Dashboard'),
			'callback' => 'cmtls_dashboard_page',
		),
	);
}

function cmtls_dashboard_cmtls_map_config()
{
	return array(
		'cmtls_dashboard' => array(
			'map views' => array(
				CMTLS_MAP_NONE,
				CMTLS_MAP_VIEW_HIDDEN,
				CMTLS_MAP_VIEW_HALF_PAGE,
				CMTLS_MAP_VIEW_FULL_PAGE,
			),
			'default map view' => CMTLS_MAP_VIEW_HIDDEN,
			'map view changable' => TRUE,
			'add from map' => TRUE,
		),
	);
}

function cmtls_dashboard_page($app_id)
{
	$group = _cmtls_group_get_current();
	
	// get all groups apps
	$result = db_query('SELECT nodehierarchy.nid FROM {nodehierarchy} nodehierarchy WHERE nodehierarchy.parent = '.(int)$group->nid.' ORDER BY order_by');
	
	$apps = array();
	
	// app blocks
	while($row = db_fetch_array($result))
	{
		$app = node_load($row['nid']);
		$app->cmtls_dashboard_content = module_invoke($app->field_cmtls_app_type[0]['value'], 'cmtls_dashboard_block_content', $group, $app);
		
		if($app->cmtls_dashboard_content) $apps[] = $app;
	}
	// widgets
	$widgets = module_invoke_all('cmtls_dashboard_widgets', $group);
	
	return theme('cmtls_dashboard_content', $apps, $widgets);
}

function hook_cmtls_dashboard_block_content($group, $app)
{
	return views_embed_view('example_view', 'example_display_id', $group->nid, $app->nid);
}

function hook_cmtls_dashboard_widgets($group)
{
	return array(
		'example_widget' => array(
			'title' => 'Example title',
			'content' => views_embed_view('example_view', 'example_display_id', $group->nid),
		),
	);
}

function cmtls_dashboard_theme($existing)
{
	return array(
		// articles page
		'cmtls_dashboard_content' => array (
			'arguments' => array('apps' => NULL, 'widgets' => NULL),
			'template' => 'cmtls-dashboard-content',
			'path' => drupal_get_path('module', 'cmtls_dashboard').'/theme',
		),
	);
}
